import = ["/home/nethunranasingha/.config/alacritty/alacritty-theme/themes/dracula.yaml"]

[cursor]
blink_interval = 750
blink_timeout = 5

[cursor.style]
blinking = "On"
shape = "Beam"

[font]
size = 9.0

[font.bold]
family = "MesloLGS NF"
style = "Bold"

[font.bold_italic]
family = "MesloLGS NF"
style = "Bold Italic"

[font.italic]
family = "MesloLGS NF"
style = "Italic"

[font.normal]
family = "MesloLGS NF"
style = "Regular"

[shell]
program = "/bin/zsh"

[window]
decorations = "none"
dynamic_title = false
opacity = 0.9
startup_mode = "Maximized"
